// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QCModule.Infrastructure.Persistence;

#nullable disable

namespace QCModule.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260609003222_AddWithinMaterialWestgardRules")]
    partial class AddWithinMaterialWestgardRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QCModule.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.AppSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Key = "login_background_preset",
                            Value = "gradient-blue"
                        },
                        new
                        {
                            Id = new Guid("b1000001-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Key = "login_circle_color",
                            Value = "blue"
                        },
                        new
                        {
                            Id = new Guid("b1000001-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Key = "login_show_circle",
                            Value = "true"
                        },
                        new
                        {
                            Id = new Guid("b1000001-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Key = "login_logo_size",
                            Value = "medium"
                        },
                        new
                        {
                            Id = new Guid("b1000001-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Key = "app_title",
                            Value = "QC Module"
                        },
                        new
                        {
                            Id = new Guid("b1000001-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Key = "app_subtitle",
                            Value = "Laboratory Quality Control"
                        },
                        new
                        {
                            Id = new Guid("c1000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Key = "file_watcher_enabled",
                            Value = "false"
                        },
                        new
                        {
                            Id = new Guid("c1000001-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Key = "file_watcher_folder_path",
                            Value = ""
                        },
                        new
                        {
                            Id = new Guid("c1000001-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Key = "file_watcher_archive_path",
                            Value = ""
                        },
                        new
                        {
                            Id = new Guid("c1000001-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Key = "file_watcher_interval_seconds",
                            Value = "30"
                        });
                });

            modelBuilder.Entity("QCModule.Domain.Entities.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TestFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TestFileId");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.QCResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AuthorisationStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AuthorisedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AuthorisedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("QCSampleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ResultDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TestFileParameterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ValidatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ValidationStatus")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.Property<string>("WestgardFlags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ZScore")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AuthorisedBy");

                    b.HasIndex("QCSampleId");

                    b.HasIndex("TestFileParameterId");

                    b.HasIndex("UserId");

                    b.HasIndex("ValidatedBy");

                    b.ToTable("QCResults");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.QCSample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NxCount")
                        .HasColumnType("int");

                    b.Property<double>("RejectSD")
                        .HasColumnType("float");

                    b.Property<bool>("Rule10x")
                        .HasColumnType("bit");

                    b.Property<bool>("Rule1_2s")
                        .HasColumnType("bit");

                    b.Property<bool>("Rule1_3s")
                        .HasColumnType("bit");

                    b.Property<bool>("Rule2_2s")
                        .HasColumnType("bit");

                    b.Property<bool>("Rule2_2sDiff")
                        .HasColumnType("bit");

                    b.Property<bool>("Rule3_1s")
                        .HasColumnType("bit");

                    b.Property<bool>("Rule4_1s")
                        .HasColumnType("bit");

                    b.Property<bool>("Rule7T")
                        .HasColumnType("bit");

                    b.Property<bool>("Rule9x")
                        .HasColumnType("bit");

                    b.Property<bool>("RuleR_4s")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.ToTable("QCSamples");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.QCSampleTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CV")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("Mean")
                        .HasColumnType("float");

                    b.Property<Guid>("QCSampleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("SD")
                        .HasColumnType("float");

                    b.Property<double?>("Tea")
                        .HasColumnType("float");

                    b.Property<string>("TeaUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TestFileParameterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("QCSampleId");

                    b.HasIndex("TestFileParameterId");

                    b.ToTable("QCSampleTargets");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full system access. Manages users, instruments, and all QC data.",
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("6313179f-7837-473a-a4d5-a1571ff9e65e"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reviews and approves QC results. Manages QC samples.",
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Supervisor"
                        },
                        new
                        {
                            Id = new Guid("b2b7d1f5-3f42-44e7-bbd5-8e04cdcf7ef7"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Inputs QC results and views reports.",
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Analyst"
                        },
                        new
                        {
                            Id = new Guid("c4c8e2a9-1d6b-4f3e-9a7c-2b5d8e0f1a3c"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authorises validated QC results (second approval layer).",
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Doctor"
                        });
                });

            modelBuilder.Entity("QCModule.Domain.Entities.TestFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TestFiles");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.TestFileParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double?>("LowerLimit")
                        .HasColumnType("float");

                    b.Property<string>("OutputMask")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("TestCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TestFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("UpperLimit")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("TestFileId");

                    b.ToTable("TestFileParameters");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.WestgardRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRejection")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWarning")
                        .HasColumnType("bit");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WestgardRules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Warning: one value exceeds ±2SD. Investigate but do not reject.",
                            IsDeleted = false,
                            IsEnabled = true,
                            IsRejection = false,
                            IsWarning = true,
                            RuleCode = "1:2s"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rejection: one value exceeds ±3SD. Random error.",
                            IsDeleted = false,
                            IsEnabled = true,
                            IsRejection = true,
                            IsWarning = false,
                            RuleCode = "1:3s"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rejection: two consecutive values exceed the same ±2SD limit.",
                            IsDeleted = false,
                            IsEnabled = true,
                            IsRejection = true,
                            IsWarning = false,
                            RuleCode = "2:2s"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rejection: range between two values in a run exceeds 4SD.",
                            IsDeleted = false,
                            IsEnabled = true,
                            IsRejection = true,
                            IsWarning = false,
                            RuleCode = "R:4s"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rejection: four consecutive values exceed the same ±1SD limit.",
                            IsDeleted = false,
                            IsEnabled = true,
                            IsRejection = true,
                            IsWarning = false,
                            RuleCode = "4:1s"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rejection: ten consecutive values fall on the same side of mean.",
                            IsDeleted = false,
                            IsEnabled = true,
                            IsRejection = true,
                            IsWarning = false,
                            RuleCode = "10:x"
                        });
                });

            modelBuilder.Entity("QCModule.Domain.Entities.ActivityLog", b =>
                {
                    b.HasOne("QCModule.Domain.Entities.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.Instrument", b =>
                {
                    b.HasOne("QCModule.Domain.Entities.TestFile", "TestFile")
                        .WithMany()
                        .HasForeignKey("TestFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TestFile");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.QCResult", b =>
                {
                    b.HasOne("QCModule.Domain.Entities.User", "AuthorisedByUser")
                        .WithMany()
                        .HasForeignKey("AuthorisedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QCModule.Domain.Entities.QCSample", "QCSample")
                        .WithMany("QCResults")
                        .HasForeignKey("QCSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QCModule.Domain.Entities.TestFileParameter", "TestFileParameter")
                        .WithMany("QCResults")
                        .HasForeignKey("TestFileParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QCModule.Domain.Entities.User", "User")
                        .WithMany("QCResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QCModule.Domain.Entities.User", "ValidatedByUser")
                        .WithMany()
                        .HasForeignKey("ValidatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AuthorisedByUser");

                    b.Navigation("QCSample");

                    b.Navigation("TestFileParameter");

                    b.Navigation("User");

                    b.Navigation("ValidatedByUser");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.QCSample", b =>
                {
                    b.HasOne("QCModule.Domain.Entities.Instrument", "Instrument")
                        .WithMany("QCSamples")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.QCSampleTarget", b =>
                {
                    b.HasOne("QCModule.Domain.Entities.QCSample", "QCSample")
                        .WithMany("Targets")
                        .HasForeignKey("QCSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QCModule.Domain.Entities.TestFileParameter", "TestFileParameter")
                        .WithMany("QCSampleTargets")
                        .HasForeignKey("TestFileParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QCSample");

                    b.Navigation("TestFileParameter");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("QCModule.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.TestFileParameter", b =>
                {
                    b.HasOne("QCModule.Domain.Entities.TestFile", "TestFile")
                        .WithMany("Parameters")
                        .HasForeignKey("TestFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestFile");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.User", b =>
                {
                    b.HasOne("QCModule.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.Instrument", b =>
                {
                    b.Navigation("QCSamples");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.QCSample", b =>
                {
                    b.Navigation("QCResults");

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.TestFile", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.TestFileParameter", b =>
                {
                    b.Navigation("QCResults");

                    b.Navigation("QCSampleTargets");
                });

            modelBuilder.Entity("QCModule.Domain.Entities.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("QCResults");
                });
#pragma warning restore 612, 618
        }
    }
}
